name: to_do_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  uuid: ^3.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  bloc_test: ^9.0.3
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
